const express = require('express')
const router = express.Router()
const { add, getPost, deletePost, updatePost, likePost } = require('../controller/productController')
const { addEpisode, fetchEpisodes, getEpisode, addComment, fetchComment } = require('../controller/episodeController')
const auth = require('../middleware/middleware')
router.post('/add', add)
router.get('/', getPost)
router.delete('/:id', deletePost)
router.patch('/:id', updatePost)
router.patch('/:id/likePost', auth, likePost)
router.post('/episode/:id', addEpisode)
router.get('/episode/:id', fetchEpisodes)
router.get('/episode/watch/:id', getEpisode)
router.post('/comment', auth, addComment)
router.get('/comment/:id', auth, fetchComment)
module.exports = router
